## NMF

In [1]:
import sys; sys.path.insert(0, '..')

from test_util.data_loader import DataLoader
from test_util.metric_calculator import MetricCalculator

In [2]:
data_loader = DataLoader(num_users=1000, num_test_items=5, data_path='../data/ml-10m')
movielens = data_loader.load()

In [3]:
user_movie_matrix = movielens.train.pivot(index='user_id', columns='movie_id', values='rating')
user_movie_matrix

movie_id,1,2,3,4,5,6,7,8,9,10,...,62000,62113,62293,62344,62394,62801,62803,63113,63992,64716
user_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1050,NaN,3.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1051,5.0,NaN,3.0,NaN,3.0,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1053,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
user_movie_matrix.fillna(0)

movie_id,1,2,3,4,5,6,7,8,9,10,...,62000,62113,62293,62344,62394,62801,62803,63113,63992,64716
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,1.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1050,0.0,3.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1051,5.0,0.0,3.0,0.0,3.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1052,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1053,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
from sklearn.decomposition import NMF
import numpy as np

user_id2index = dict(zip(user_movie_matrix.index, range(len(user_movie_matrix.index))))
movie_id2index = dict(zip(user_movie_matrix.columns, range(len(user_movie_matrix.columns))))
matrix = user_movie_matrix.fillna(movielens.train.rating.mean()).to_numpy()

nmf = NMF(n_components=5)
nmf.fit(matrix)
P = nmf.fit_transform(matrix)
Q = nmf.components_

pred_matrix = np.dot(P, Q)

print(f"P: {P.shape}, Q: {Q.shape}, pred_matrix: {pred_matrix.shape}")

P: (1000, 5), Q: (5, 6669), pred_matrix: (1000, 6669)

In [7]:
P, Q

(array([[9.85414364e-02, 1.50909150e-01, 6.82880577e-01, 5.16233053e-01,
         1.65081073e-01],
        [2.80249950e-01, 2.94562618e-02, 1.03733834e-04, 1.32224189e-01,
         9.14873678e-01],
        [2.80864663e-01, 2.91213182e-02, 1.30664457e-04, 1.33178917e-01,
         9.15108891e-01],
        ...,
        [0.00000000e+00, 7.56481439e-04, 1.57520480e-01, 4.09054259e-01,
         7.79659001e-01],
        [2.79703720e-01, 3.01719920e-02, 1.14858828e-04, 1.31200000e-01,
         9.15570575e-01],
        [2.80854532e-01, 4.13507916e-02, 0.00000000e+00, 1.11430146e-01,
         9.21360012e-01]]),
 array([[1.53560817, 1.38123729, 1.4153926 , ..., 1.03023602, 1.03115091,
         1.029516  ],
        [3.60144856, 2.73743319, 2.8155133 , ..., 0.        , 0.        ,
         0.        ],
        [2.36703903, 2.22746902, 2.21756615, ..., 3.76874461, 3.76756035,
         3.76620811],
        [2.18002723, 2.08668575, 2.06710711, ..., 0.61966966, 0.62111707,
         0.62430245],
        [3.13151478, 2.97401843, 2.99818855, ..., 3.50340904, 3.50292114,
         3.50099877]]))

In [8]:
from test_src.nmf import NMFRecommender
recommender = NMFRecommender()
recommend_result = recommender.recommend(movielens)

c:\Users\eunjo\anaconda3\envs\rec_sys_2024\lib\site-packages\sklearn\decomposition\_nmf.py:1759: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(
c:\Users\eunjo\anaconda3\envs\rec_sys_2024\lib\site-packages\sklearn\decomposition\_nmf.py:1759: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(

In [9]:
metric_calculator = MetricCalculator()
metrics = metric_calculator.calc(
    movielens.test.rating.tolist(), recommend_result.rating.tolist(),
    movielens.test_user2items, recommend_result.user2items, k=10
)
print(metrics)

rmse=3.336, Precision@K=0.011, Recall@K=0.038